Remove course syllabus block (without compiled assets)
gocodebox/lifterlms-blocks pull request #187
Opened 2023-03-08 14:04 UTC by seothemes

## Description

This PR removes the Course Syllabus block since an updated version has been added to the core LifterLMS plugin.

## How has this been tested?

- Manually tested
- PHPUnit

## Types of changes

Breaking change - This could cause issues if a site has an old version of the core LifterLMS plugin without the new syllabus block.

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests.
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2023-03-08 14:05 UTC, seothemes commented
Related https://github.com/gocodebox/lifterlms/pull/2374

2023-04-11 10:36 UTC, eri-trabiccolo requested changes
Thanks for this @seothemes 
Looking at it, though, since it's an extending class, I think we need to override all the public and protected methods and deprecated them as well, what do you think?

2023-04-26 07:52 UTC, seothemes commented
@eri-trabiccolo I have made these changes if you'd like to take a look https://github.com/gocodebox/lifterlms-blocks/pull/187/commits/622de3f9ce8edea2b8fa150d4476d040090b70aa

2023-04-26 08:31 UTC, eri-trabiccolo requested changes
I think it's good.
Do you have the time to fix the failing PHP unit tests?
I think you can just get rid of the tests on this "component".

2023-06-01 09:44 UTC, eri-trabiccolo approved these changes

2023-06-01 14:37 UTC, eri-trabiccolo requested changes

2023-06-01 14:37 UTC, eri-trabiccolo commented on includes/blocks/class-llms-blocks-course-syllabus-block.php
> +	 * @param string $content Optional. Block content. Default empty string.
```suggestion
	 * @param array  $attributes Optional. Block attributes. Default empty array.
	 * @param string $content    Optional. Block content. Default empty string.
```

2023-06-01 14:37 UTC, eri-trabiccolo commented on includes/blocks/class-llms-blocks-course-syllabus-block.php
> +	 * Extending classes can use this class to remove hooks attached to the render function action.
```suggestion
	 * Removed hooks stub.
	 *
	 * Extending classes can use this class to remove hooks attached to the render function action.
```

2023-06-01 14:37 UTC, eri-trabiccolo commented on includes/blocks/class-llms-blocks-course-syllabus-block.php
> +	 * @param string $content Optional. Block content. Default empty string.
```suggestion
	 * @param array  $attributes Optional. Block attributes. Default empty array.
	 * @param string $content    Optional. Block content. Default empty string.
```

2023-06-01 14:38 UTC, eri-trabiccolo approved these changes

2023-06-01 14:52 UTC, merged