Use imports in favor of references to `window.wp`
gocodebox/lifterlms-blocks pull request #82
Opened 2021-03-02 18:07 UTC by thomasplevy

## Description

Replaces all (maybe most) references to modules on `window.wp` with imports from the equivalent `@wordpress` package.

Fixes #77

## How has this been tested?

Manually

## Screenshots 

## Types of changes

Bugfix

## Checklist:

- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-03-03 10:13 UTC, eri-trabiccolo requested changes
Mmm,
what's the minimum wp version we're going to support after this changes?

2021-03-03 10:13 UTC, eri-trabiccolo commented on src/js/blocks.js
> + * @since [version] Disable import of incomplete modue `./formats/merge-codes`;
```suggestion
 * @since [version] Disable import of incomplete modue `./formats/merge-codes`.
```

2021-03-05 23:44 UTC, thomasplevy commented
> Mmm,
> what's the minimum wp version we're going to support after this changes?

This question just made my head explode... I had totally forgotten that even though WP throws deprecation warnings... the replacements aren't backported and if we follow the advice of the deprecation warnings we create issues like #62 which are a nightmare to figure out how to fix. Advice from the core is to *include* the missing packages in our build and load it conditionally in the required version of WP.

This isn't terribly complicated to do but the problem then becomes that we need to know what versions of WP a given package was shipped with in order to figure out which packages we need to backport and load conditionally.

Since we're about to drop support for 5.2 (see https://github.com/gocodebox/lifterlms/pull/1551) we can "safely" say 5.3 will be the minimum supported version.

So then we also need to go and figure out all the packages I've updated for consistencies sake without considering backwards compatiblity.

WHAT A NIGHTMARE THIS INSTANTLY BECAME.

If we review the changelogs on the packages they're recorded in the gutenberg plugin's version number, not in the version number of the core version it was included in. Furthermore, we need to look at individual components imported from the various packages, not just the packages themselves.

So there's no quick way to do this unless we actually have full e2e test coverage to let our tests tell us where things are failing.

I think the best bet is to load up 5.3 - 5.7, load the block editor for a course (and a form) and see if it breaks.

If i doesn't break lets say it works, if it doesn't we'll record it and research the error message on it's own to figure out backwards compat.

2021-03-05 23:46 UTC, thomasplevy commented
@eri-trabiccolo I'm sorry for my last commit... I had to get the eslint stuff in place before I lost my mind.

2021-03-22 20:13 UTC, merged